import funcionesSQL
from funcionesSQL import baseDeDatos
from funcionesSQL import cursorBaseDeDatos

def comandoSQLParaCrearBaseDeDatosNueva():
    comandoSQL = """ CREATE TABLE IF NOT EXISTS AREAS(ID_AREA INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE_AREA TEXT);
    CREATE TABLE IF NOT EXISTS MARCAS(ID_MARCA INTEGER PRIMARY KEY AUTOINCREMENT,NOMBRE_MARCA TEXT);
    CREATE TABLE IF NOT EXISTS ARTICULOS(
    CODIGO_DE_BARRA INTEGER PRIMARY KEY,
    NOMBRE_ARTICULO TEXT,
    PRECIO INTEGER,
    ARTICULO_MARCA INTEGER,
    ARTICULO_AREA INTEGER,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    STOCK INTEGER,
    FOREIGN KEY (ARTICULO_MARCA) REFERENCES MARCAS(ID_MARCA),
    FOREIGN KEY (ARTICULO_AREA) REFERENCES AREAS(ID_AREA));
    CREATE TRIGGER ACT_FECHA AFTER UPDATE OF PRECIO ON ARTICULOS FOR EACH ROW BEGIN UPDATE ARTICULOS SET FECHA = CURRENT_TIMESTAMP;END;
    """
    return comandoSQL

def crearBaseDeDatosNueva():
    funcionesSQL.conectarConBaseDeDatos()
    funcionesSQL.tomarCursor()
    comandoSQL = comandoSQLParaCrearBaseDeDatosNueva()
    funcionesSQL.ejecutarVariosComandos(comandoSQL)
    funcionesSQL.guardarBaseDeDatos(baseDeDatos)

